### ISSUE TITLE
ValueError: You must supply the dataset directory with --dataset_dir

### ISSUE THREAD

**Issue by Dgs29** [ZJULearning/pixel_link#102]
How do i specify the dataset location. What is the path that I need to add?  I have downloaded ch4_test_images and ch4_training_images and stored them in dataset/ICDAR2015/Challenge4/. 

As I run the test script, I get the error: ValueError: You must supply the dataset directory with --dataset_dir

**Comment by ajinkya933** [comment]
Hi @Dgs29  I have the same problem. How can you solve it ?
