### ISSUE TITLE
icdar2015_to_tfrecords.py error

### ISSUE THREAD

**Issue by wangwj** [ZJULearning/pixel_link#108]
python  icdar2015_to_tfrecords.py 
ImportError: No module named config

config 是什么库，用pip安装config好像不行

**Comment by jiaying96** [comment]
![image](https://user-images.githubusercontent.com/16167043/53535916-5c5ba880-3b3f-11e9-9615-82e6ee1c22ba.png)
config在这

**Comment by wangwj** [comment]
@jiaying96  谢谢、已经发现
