### ISSUE TITLE
结果没有显示在存放测试图片的文件夹

### ISSUE THREAD

**Issue by jiaying96** [ZJULearning/pixel_link#111]
./scripts/test_any.sh 1 model/2s/model.ckpt-73018 test
结果图片不在test文件夹，而是

![image](https://user-images.githubusercontent.com/16167043/53311120-941de280-38ea-11e9-8b95-b38e8d86b8fb.png)

而且颜色变化
按照作者所说，结果应该直接在存放测试图片的文件夹test中，是出错了吗

**Comment by snowwindy** [comment]
我的也是这样，保存的图片只有颜色的变化，没有检测框

**Comment by snowwindy** [comment]
@jiaying96 你好，我想问一下，你的这个问题解决了吗？怎么解决的

**Comment by jiaying96** [comment]
@snowwindy 解决了
执行    ./scripts/test.sh 1 model/2s/model.ckpt-73018 test
生成  zip:model/2s/test/icdar2015_test/model.ckpt-73018/model.ckpt-73018_det.zip
将model.ckpt-73018_det.zip解压放在det文件夹下
执行：scripts/vis.sh test det
test为图片路径  det为txt路径(将zip文件解压后txt放入det文件夹)
