### ISSUE TITLE
File not found:/pixel_link-master/dataset/ICDAR2015/Challenge4/ch4_training_images/img_9312.jpg

### ISSUE THREAD

**Issue by jiaying96** [ZJULearning/pixel_link#115]
![image](https://user-images.githubusercontent.com/16167043/53536541-c83f1080-3b41-11e9-9a81-3401386d7c06.png)

执行python  icdar2015_to_tfrecords.py
有这个文件却找不到  是因为数据集大吗

**Comment by sshkhr** [comment]
I'm getting a similar issue while running on a folder of images. The file is present but gives IOError. How did you resolve this ?
