### ISSUE TITLE
Loss around 0.4 ~0.5, and predict empty box 

### ISSUE THREAD

**Issue by jisheng047** [ZJULearning/pixel_link#144]
After training about 20k iters, my loss still around 0.4 ~ 0.5. And pick up the model to predict, what i receive is empty box? 

Can anyone know how to fine tune the model? Please help me out this problem, thanks you

**Comment by ajinkya933** [comment]
@jisheng047 how did you solve

**Comment by jisheng047** [comment]
@ajinkya933 Keep training until 250k - 300k steps, loss will drop out to 0.2-0.3.
