### ISSUE TITLE
ImportError: No module named util

### ISSUE THREAD

**Issue by dajiangxiaoyan** [ZJULearning/pixel_link#23]
![image](https://user-images.githubusercontent.com/17979833/40697261-fdc0859a-63fb-11e8-820f-acd2e66a8d89.png)

Thank you very much for sharing code. Its beautiful. 
But i can not find this python module?

**Comment by snowwindy** [comment]
@pymia @dajiangxiaoyan 我遇到了同样的问题，没解决，还是说找不到util
