### ISSUE TITLE
训练的时候不输出loss

### ISSUE THREAD

**Issue by LiangHao92** [ZJULearning/pixel_link#31]
你好，我想请问一下。我先用icdar的数据试了一下训练，没有问题，loss正常输出。然后我用自己的数据生成了tfrecord格式来训练，但训练的时候不输出loss，只是模型的数据在一直更新，请问这是什么情况

**Comment by wanghuok** [comment]
我用自己的数据集训练的时候loss一直等于0,这是咋回事？
