### ISSUE TITLE
no module named util

### ISSUE THREAD

**Issue by zwz7712** [ZJULearning/pixel_link#4]
谢作者分享，还在初学阶段
同之前那个提问一样，在运行test.sh时，出现：
Traceback (most recent call last):
  File "test_pixel_link.py", line 8, in <module>
    from datasets import dataset_factory
  File "/home/zht/study/PixelLink/pixel_link-master/datasets/dataset_factory.py", line 2, in <module>
    from datasets import dataset_utils
  File "/home/zht/study/PixelLink/pixel_link-master/datasets/dataset_utils.py", line 21, in <module>
    import util
ImportError: No module named 'util'
同没有找到util这个文件在哪，求指教，谢谢。

**Comment by lw19951231** [comment]
你需要设置pythonpath的路径
export PYTHONPATH=${path_to_pixel_link}/pylib/src:$PYTHONPATH

**Comment by cdsss** [comment]
> git submodule update --init --recursive

When I try to do this, I get results:

> (dl) root@682b431e7d09:/input/pixel_link# git submodule update --init --recursive
正克隆到 'pylib'...
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
fatal: 无法克隆 'git@github.com:dengdan/pylib.git' 到子模组路径 'pylib'

can you help me solve this problem? thank you

**Comment by Elsanna** [comment]
在服务器运行程序没有问题，但是在本地Pycharm上面就报importError: No module named util，求解答是什么原因

**Comment by jun214384468** [comment]
> 在服务器运行程序没有问题，但是在本地Pycharm上面就报importError: No module named util，求解答是什么原因
我也是想问这个问题，在pycharm中怎么改呢？你解决了吗？能不能指点我一下，谢谢

**Comment by banana47** [comment]
> 谢作者分享，还在初学阶段
> 同之前那个提问一样，在运行test.sh时，出现：
> Traceback (most recent call last):
> File "test_pixel_link.py", line 8, in
> from datasets import dataset_factory
> File "/home/zht/study/PixelLink/pixel_link-master/datasets/dataset_factory.py", line 2, in
> from datasets import dataset_utils
> File "/home/zht/study/PixelLink/pixel_link-master/datasets/dataset_utils.py", line 21, in
> import util
> ImportError: No module named 'util'
> 同没有找到util这个文件在哪，求指教，谢谢。
我也遇到了这个问题，请问您怎么解决的
