### ISSUE TITLE
save model as a pb file

### ISSUE THREAD

**Issue by ciciphus** [ZJULearning/pixel_link#46]
Has anyone successfully save the model as a pb file?
when I try to inspect the pbtxt graph with 
`bazel-bin/tensorflow/tools/graph_transforms/summarize_graph --in_graph=graph.pbtxt`
I got 

> Found 351 possible outputs: (name=icdar2015_data_provider/parallel_read/filenames/filenames_EnqueueMany, op=QueueEnqueueManyV2) (name=icdar2015_data_provider/parallel_read/filenames/filenames_Close, op=QueueCloseV2) (name=icdar2015_data_provider/parallel_read/filenames/filenames_Close_1, op=QueueCloseV2) (name=icdar2015_data_provider/parallel_read/common_queue_enqueue, op=QueueEnqueueV2) (name=icdar2015_data_provider/parallel_read/common_queue_Close, op=QueueCloseV2) (name=icdar2015_data_provider/parallel_read/common_queue_Close_1, op=QueueCloseV2) (name=icdar2015_data_provider/Reshape_1, op=Reshape) (name=icdar2015_data_provider/Reshape_3, op=Reshape) (name=icdar2015_data_provider/case/cond/switch_t, op=Identity) (name=icdar2015_data_provider/case/cond/cond_jpeg/switch_t, op=Identity) (name=icdar2015_data_provider/case/cond/cond_jpeg/decode_image/cond_jpeg/cond_png/switch_t, op=Identity) (name=ssd_preprocessing_train/cond/switch_f, op=Identity) (name=ssd_preprocessing_train/cond/random_rotate90/strided_slice, op=StridedSlice) (name=ssd_preprocessing_train/cond/random_rotate90/strided_slice_1, op=StridedSlice) (name=ssd_preprocessing_train/cond/random_rotate90/rot90/cond/switch_f, op=Identity) (name=ssd_preprocessing_train/cond/random_rotate90/rot90/cond/cond/switch_f, op=Identity) (name=ssd_preprocessing_train/cond/random_rotate90/rot90/cond/cond/cond/switch_f, op=Identity) (name=ssd_preprocessing_train/distorted_bounding_box_crop/cond/switch_t, op=Identity) (name=ssd_preprocessing_train/resize_image/unstack, op=Unpack) (name=icdar2015_batch/batch/fifo_queue_enqueue, op=QueueEnqueueV2) (name=icdar2015_batch/batch/fifo_queue_Close, op=QueueCloseV2) (name=icdar2015_batch/batch/fifo_queue_Close_1, op=QueueCloseV2) (name=icdar2015_prefetch_queue/prefetch_queue/fifo_queue_enqueue, op=QueueEnqueueV2) (name=icdar2015_prefetch_queue/prefetch_queue/fifo_queue_Close, op=QueueCloseV2) (name=icdar2015_prefetch_queue/prefetch_queue/fifo_queue_Close_1, op=QueueCloseV2) (name=clone_0/pixel_cls/strided_slice, op=StridedSlice) (name=clone_0/pixel_link/strided_slice, op=StridedSlice) (name=clone_0/strided_slice_3, op=StridedSlice) (name=clone_0/strided_slice_4, op=StridedSlice) (name=count_warning/read, op=Identity) (name=clone_0/add_1, op=Add) (name=clone_0/gradients/clone_0/truediv_grad/tuple/control_dependency_1, op=Identity) (name=clone_0/gradients/clone_0/conv1/conv1_1/kernel/Regularizer/l2_regularizer_grad/tuple/control_dependency, op=Identity) (name=clone_0/gradients/clone_0/conv1/conv1_2/kernel/Regularizer/l2_regularizer_grad/tuple/control_dependency, op=Identity) (name=clone_0/gradients/clone_0/conv2/conv2_1/kernel/Regularizer/l2_regularizer_grad/tuple/control_dependency, op=Identity) (name=clone_0/gradients/clone_0/conv2/conv2_2/kernel/Regularizer/l2_regularizer_grad/tuple/control_dependency, op=Identity) (name=clone_0/gradients/clone_0/conv3/conv3_1/kernel/Regularizer/l2_regularizer_grad/tuple/control_dependency, op=Identity) (name=clone_0/gradients/clone_0/conv3/conv3_2/kernel/Regularizer/l2_regularizer_grad/tuple/control_dependency, op=Identity) (name=clone_0/gradients/clone_0/conv3/conv3_3/kernel/Regularizer/l2_regularizer_grad/tuple/control_dependency, op=Identity) (name=clone_0/gradients/clone_0/conv4/conv4_1/kernel/Regularizer/l2_regularizer_grad/tuple/control_dependency, op=Identity) (name=clone_0/gradients/clone_0/conv4/conv4_2/kernel/Regularizer/l2_regularizer_grad/tuple/control_dependency, op=Identity) (name=clone_0/gradients/clone_0/conv4/conv4_3/kernel/Regularizer/l2_regularizer_grad/tuple/control_dependency, op=Identity) (name=clone_0/gradients/clone_0/conv5/conv5_1/kernel/Regularizer/l2_regularizer_grad/tuple/control_dependency, op=Identity) (name=clone_0/gradients/clone_0/conv5/conv5_2/kernel/Regularizer/l2_regularizer_grad/tuple/control_dependency, op=Identity) (name=clone_0/gradients/clone_0/conv5/conv5_3/kernel/Regularizer/l2_regularizer_grad/tuple/control_dependency, op=Identity) (name=clone_0/gradients/clone_0/fc6/kernel/Regularizer/l2_regularizer_grad/tuple/control_dependency, op=Identity) (name=clone_0/gradients/clone_0/fc7/kernel/Regularizer/l2_regularizer_grad/tuple/control_dependency, op=Identity) (name=clone_0/gradients/clone_0/pixel_cls/score_from_fc7/kernel/Regularizer/l2_regularizer_grad/tuple/control_dependency, op=Identity) (name=clone_0/gradients/clone_0/pixel_cls/score_from_conv5_3/kernel/Regularizer/l2_regularizer_grad/tuple/control_dependency, op=Identity) (name=clone_0/gradients/clone_0/pixel_cls/score_from_conv4_3/kernel/Regularizer/l2_regularizer_grad/tuple/control_dependency, op=Identity) (name=clone_0/gradients/clone_0/pixel_cls/score_from_conv3_3/kernel/Regularizer/l2_regularizer_grad/tuple/control_dependency, op=Identity) (name=clone_0/gradients/clone_0/pixel_link/score_from_fc7/kernel/Regularizer/l2_regularizer_grad/tuple/control_dependency, op=Identity) (name=clone_0/gradients/clone_0/pixel_link/score_from_conv5_3/kernel/Regularizer/l2_regularizer_grad/tuple/control_dependency, op=Identity) (name=clone_0/gradients/clone_0/pixel_link/score_from_conv4_3/kernel/Regularizer/l2_regularizer_grad/tuple/control_dependency, op=Identity) (name=clone_0/gradients/clone_0/pixel_link/score_from_conv3_3/kernel/Regularizer/l2_regularizer_grad/tuple/control_dependency, op=Identity) (name=clone_0/gradients/clone_0/pixel_cls_loss/mul_1_grad/tuple/control_dependency_1, op=Identity) (name=clone_0/gradients/clone_0/pixel_link_loss/mul_1_grad/tuple/control_dependency, op=Identity) (name=clone_0/gradients/clone_0/pixel_cls_loss/truediv_grad/tuple/control_dependency_1, op=Identity) (name=clone_0/gradients/clone_0/pixel_link_loss/cond/Merge_1_grad/tuple/control_dependency, op=Identity) (name=clone_0/gradients/clone_0/pixel_link_loss/mul_grad/tuple/control_dependency_1, op=Identity) (name=clone_0/gradients/clone_0/pixel_cls_loss/mul_grad/tuple/control_dependency_1, op=Identity) (name=clone_0/gradients/clone_0/pixel_link_loss/cond/truediv_1_grad/tuple/control_dependency_1, op=Identity) (name=clone_0/gradients/clone_0/pixel_link_loss/cond/Merge_grad/tuple/control_dependency, op=Identity) (name=clone_0/gradients/clone_0/pixel_link_loss/cond/truediv_grad/tuple/control_dependency_1, op=Identity) (name=clone_0/gradients/zeros_like, op=ZerosLike) (name=clone_0/gradients/clone_0/pixel_link_loss/cond/mul_3_grad/tuple/control_dependency_1, op=Identity) (name=clone_0/gradients/clone_0/pixel_link_loss/cond/mul_1_grad/tuple/control_dependency_1, op=Identity) (name=clone_0/gradients/zeros_like_1, op=ZerosLike) (name=clone_0/gradients/clone_0/conv1/conv1_1/Conv2D_grad/tuple/control_dependency, op=Identity) (name=conv1/conv1_1/weights/Momentum/read, op=Identity) (name=conv1/conv1_1/biases/Momentum/read, op=Identity) (name=conv1/conv1_2/weights/Momentum/read, op=Identity) (name=conv1/conv1_2/biases/Momentum/read, op=Identity) (name=conv2/conv2_1/weights/Momentum/read, op=Identity) (name=conv2/conv2_1/biases/Momentum/read, op=Identity) (name=conv2/conv2_2/weights/Momentum/read, op=Identity) (name=conv2/conv2_2/biases/Momentum/read, op=Identity) (name=conv3/conv3_1/weights/Momentum/read, op=Identity) (name=conv3/conv3_1/biases/Momentum/read, op=Identity) (name=conv3/conv3_2/weights/Momentum/read, op=Identity) (name=conv3/conv3_2/biases/Momentum/read, op=Identity) (name=conv3/conv3_3/weights/Momentum/read, op=Identity) (name=conv3/conv3_3/biases/Momentum/read, op=Identity) (name=conv4/conv4_1/weights/Momentum/read, op=Identity) (name=conv4/conv4_1/biases/Momentum/read, op=Identity) (name=conv4/conv4_2/weights/Momentum/read, op=Identity) (name=conv4/conv4_2/biases/Momentum/read, op=Identity) (name=conv4/conv4_3/weights/Momentum/read, op=Identity) (name=conv4/conv4_3/biases/Momentum/read, op=Identity) (name=conv5/conv5_1/weights/Momentum/read, op=Identity) (name=conv5/conv5_1/biases/Momentum/read, op=Identity) (name=conv5/conv5_2/weights/Momentum/read, op=Identity) (name=conv5/conv5_2/biases/Momentum/read, op=Identity) (name=conv5/conv5_3/weights/Momentum/read, op=Identity) (name=conv5/conv5_3/biases/Momentum/read, op=Identity) (name=fc6/weights/Momentum/read, op=Identity) (name=fc6/biases/Momentum/read, op=Identity) (name=fc7/weights/Momentum/read, op=Identity) (name=fc7/biases/Momentum/read, op=Identity) (name=pixel_cls/score_from_fc7/weights/Momentum/read, op=Identity) (name=pixel_cls/score_from_fc7/biases/Momentum/read, op=Identity) (name=pixel_cls/score_from_conv5_3/weights/Momentum/read, op=Identity) (name=pixel_cls/score_from_conv5_3/biases/Momentum/read, op=Identity) (name=pixel_cls/score_from_conv4_3/weights/Momentum/read, op=Identity) (name=pixel_cls/score_from_conv4_3/biases/Momentum/read, op=Identity) (name=pixel_cls/score_from_conv3_3/weights/Momentum/read, op=Identity) (name=pixel_cls/score_from_conv3_3/biases/Momentum/read, op=Identity) (name=pixel_link/score_from_fc7/weights/Momentum/read, op=Identity) (name=pixel_link/score_from_fc7/biases/Momentum/read, op=Identity) (name=pixel_link/score_from_conv5_3/weights/Momentum/read, op=Identity) (name=pixel_link/score_from_conv5_3/biases/Momentum/read, op=Identity) (name=pixel_link/score_from_conv4_3/weights/Momentum/read, op=Identity) (name=pixel_link/score_from_conv4_3/biases/Momentum/read, op=Identity) (name=pixel_link/score_from_conv3_3/weights/Momentum/read, op=Identity) (name=pixel_link/score_from_conv3_3/biases/Momentum/read, op=Identity) (name=cond/switch_t, op=Identity) (name=cond/switch_f, op=Identity) (name=cond/Merge, op=Merge) (name=conv1/conv1_1/weights/ExponentialMovingAverage/cond/switch_t, op=Identity) (name=conv1/conv1_1/weights/ExponentialMovingAverage/cond/switch_f, op=Identity) (name=cond_1/switch_t, op=Identity) (name=cond_1/switch_f, op=Identity) (name=cond_1/Merge, op=Merge) (name=conv1/conv1_1/biases/ExponentialMovingAverage/cond/switch_t, op=Identity) (name=conv1/conv1_1/biases/ExponentialMovingAverage/cond/switch_f, op=Identity) (name=cond_2/switch_t, op=Identity) (name=cond_2/switch_f, op=Identity) (name=cond_2/Merge, op=Merge) (name=conv1/conv1_2/weights/ExponentialMovingAverage/cond/switch_t, op=Identity) (name=conv1/conv1_2/weights/ExponentialMovingAverage/cond/switch_f, op=Identity) (name=cond_3/switch_t, op=Identity) (name=cond_3/switch_f, op=Identity) (name=cond_3/Merge, op=Merge) (name=conv1/conv1_2/biases/ExponentialMovingAverage/cond/switch_t, op=Identity) (name=conv1/conv1_2/biases/ExponentialMovingAverage/cond/switch_f, op=Identity) (name=cond_4/switch_t, op=Identity) (name=cond_4/switch_f, op=Identity) (name=cond_4/Merge, op=Merge) (name=conv2/conv2_1/weights/ExponentialMovingAverage/cond/switch_t, op=Identity) (name=conv2/conv2_1/weights/ExponentialMovingAverage/cond/switch_f, op=Identity) (name=cond_5/switch_t, op=Identity) (name=cond_5/switch_f, op=Identity) (name=cond_5/Merge, op=Merge) (name=conv2/conv2_1/biases/ExponentialMovingAverage/cond/switch_t, op=Identity) (name=conv2/conv2_1/biases/ExponentialMovingAverage/cond/switch_f, op=Identity) (name=cond_6/switch_t, op=Identity) (name=cond_6/switch_f, op=Identity) (name=cond_6/Merge, op=Merge) (name=conv2/conv2_2/weights/ExponentialMovingAverage/cond/switch_t, op=Identity) (name=conv2/conv2_2/weights/ExponentialMovingAverage/cond/switch_f, op=Identity) (name=cond_7/switch_t, op=Identity) (name=cond_7/switch_f, op=Identity) (name=cond_7/Merge, op=Merge) (name=conv2/conv2_2/biases/ExponentialMovingAverage/cond/switch_t, op=Identity)

which stops me from saving it as a pb file.
Is there a way to save this model as a pb file?

**Comment by mohamad-hoseini** [comment]
Did you finally manage to convert the checkpoint model to .pb file or not?
I appreciate if you could help. I'm dealing with the same problem.
The model is too complex that I can't work out what the input and output nodes are.
