### ISSUE TITLE
training using cpu only

### ISSUE THREAD

**Issue by MrOCR** [ZJULearning/pixel_link#65]
how can I train using only cpu?

**Comment by Tianxiaomo** [comment]
I have the same problem，did you solve it?Thinks.

**Comment by ghost** [comment]
yes, I did

**Comment by Tianxiaomo** [comment]
Can you tell me how to solve this problem?thanks⸜(* ॑꒳ ॑* )⸝

**Comment by mahbubcseju** [comment]
@MrOCR  Will you please say something about how to use using only CPU .

**Comment by ghost** [comment]
@Tianxiaomo I bought a GPU.
Because training such complex models is built for gpu.
