### ISSUE TITLE
当文字在图片里面很小，mask又是原图的1/4,那么无法检测出来

### ISSUE THREAD

**Issue by northeastsquare** [ZJULearning/pixel_link#91]
我测试一些图片，发现，当文字在图片里面很小，mask又是原图的1/4,那么文字是无法无法检测出来，
而CTPN是可以检测出来的。
pixel-link面对这个缺陷，该如何改进呢？

**Comment by austingg** [comment]
@northeastsquare  具体有多小呢？ 是不是后处理的时候过滤掉了

**Comment by northeastsquare** [comment]
嗯嗯，确实是后处理给去掉了
w,h:575*766, 文字高度11
图片没有缩放，我看到生成mask，里面有一些行的一部分被检测出来
在def mask_to_bboxes：config.min_height=10，也会把这样的给直接去掉了
另外训练的时候，config.py里面min_shorter_side = 10，把小样本都被设置成label_ignore了，

我再训练一下，最小边设置为4, 在生成一些text很小的图片，在训练了，看看结果如何

**Comment by northeastsquare** [comment]
反馈一下，random scale（0.2--0.7）, pad ,生成了很多text很小的样本，训练处理后，能检测小text了
![2i4t5v l](https://user-images.githubusercontent.com/3086078/51435951-3a5c4400-1cbe-11e9-97f2-75da2d982664.PNG)
